### ISSUE TITLE
RuntimeError: CUDA out of memory.

### ISSUE THREAD

**Issue by mayanktiwariiiitdmj** [levindabhi/cloth-segmentation#10]
Hello,
Thank you for providing the source code of this project.
I need to run the code on my own machine having 6 GB GPU.
When I am doing so, I am getting the following error:
```
RuntimeError: CUDA out of memory. Tried to allocate 12.00 MiB (GPU 0; 6.00 GiB total capacity; 5.30 GiB already allocated; 0 bytes free; 5.32 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

Can you please help me in solving this error?

**Comment by mayanktiwariiiitdmj** [comment]
I have solved the problem by reducing the HD image size to 25%. Now the code is running in my system having 6GB of GPU.
